Update scan.yml

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -73,4 +73,10 @@ jobs:
           nuclei -id http-missing-security-headers -l urls_for_nuclei.txt -silent -o nuclei_results.txt
           
           echo "Nuclei scan complete. Results saved to nuclei_results.txt"
-          cat nuclei_results.txt
+          # cat nuclei_results.txt
+          # Check if the results file is not empty (-s checks for size > 0)
+          if [ -s nuclei_results.txt ]; then
+              exit 1 # This command fails the step and the job
+          else
+              echo "✅ No vulnerabilities were found in the API endpoints."
+          fi
